baseURL = 'https://blog.huydang.dev/'
canonifyURLs = false
relativeURLs = true
languageCode = 'en-us'
title = 'Huy Dang Blog'
theme = 'hugo-PaperModX'
enableRobotsTXT = true
publishDir = "docs"

[server]
baseURL = 'https://blog.huydang.dev/'

[pagination]
pagerSize = 10

[params]
description = 'Where I save and share anything I like about tech.'
author = 'huydq96'
defaultTheme = 'light'
ShowShareButtons = true
ShowCodeCopyButtons = true
ShowReadingTime = true
ShowToc = true
TocSide = 'right'
TocOpen = true
ShowComments = false
comments = false  # Enable comments in Hugo

[params.homeInfoParams]
Title = "Hi, I'm Huy"
Content = """
I'm a software engineer and a tech enthusiast.\n
This is my blog where I save and share anything I like about tech.
"""

[[params.socialIcons]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/huydq96/"

[[params.socialIcons]]
name = "GitHub"
url = "https://github.com/huydq96"

[[params.socialIcons]]
name = "Gmail"
url = "mailto:huydq96hp@gmail.com"

[[params.socialIcons]]
name = "Phone"
url = "tel:+84339485241"

[menu]
[[menu.main]]
identifier = 'post'
name = 'Posts'
url = '/posts/'
weight = 10
[[menu.main]]
identifier = 'categories'
name = 'Categories'
url = '/categories/'
weight = 20
[[menu.main]]
identifier = 'tags'
name = 'Tags'
url = '/tags/'
weight = 30

[permalinks]
posts = '/posts/:slug/'
categories = '/categories/:slug/'
tags = '/tags/:slug/'

[build]
noJSConfigInAssets = true
useResourceCacheWhen = 'fallback'
[build.buildStats]
disableClasses = false
disableIDs = false
disableTags = false
enable = false
[[build.cacheBusters]]
source = '(postcss|tailwind)\.config\.js'
target = '(css|styles|scss|sass)'
[build.minify]
disableHTML = false
publishDir = "docs"

[outputs]
home = ['html']
page = ['html']
section = ['html']
taxonomy = ['html']
term = ['html']

[taxonomies]
category = 'categories'
series = 'series'
tag = 'tags'


[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = "dracula"
lineNos = true
lineNumbersInTable = true
noClasses = false
hl_Lines = ""
lineNoStart = 1
tabWidth = 4
guessSyntax = true